--Reset database--
DROP TABLE MISALUMNOS CASCADE CONSTRAINTS;
DROP TABLE MIMATRICULAR CASCADE CONSTRAINTS;
--Inicializar la base de datos--
CREATE TABLE MISALUMNOS (
    "DNI" NUMBER (9, 0) PRIMARY KEY,
    "NOMBRE" VARCHAR2 (20 BYTE),
    "APELLIDO1" VARCHAR2 (20 BYTE),
    "APELLIDO2" VARCHAR2 (20 BYTE),
    "GENERO" VARCHAR2 (4 BYTE),
    "EMAIL" VARCHAR2 (40 BYTE),
    "FECHA_NACIMIENTO" DATE,
    "FECHA_PRIM_MATRICULA" DATE
);
--1--
insert into MISALUMNOS
select A.DNI,
    A.NOMBRE,
    A.APELLIDO1,
    A.APELLIDO2,
    A.GENERO,
    A.EMAIL,
    A.FECHA_NACIMIENTO,
    A.FECHA_PRIM_MATRICULA
from DOCENCIA.ALUMNOS A
    join DOCENCIA.PROVINCIA P on A.CPRO = P.CODIGO
where P.NOMBRE = 'Málaga';
--2--
update MISALUMNOS
set NOMBRE = upper(NOMBRE),
    APELLIDO1 = upper(APELLIDO1),
    APELLIDO2 = upper(APELLIDO2);
--3--
CREATE TABLE MIMATRICULAR AS
SELECT *
FROM DOCENCIA.MATRICULAR;
--4--
delete from MIMATRICULAR
where ALUMNO not in (
        select DNI
        from MISALUMNOS
    );
--5--
INSERT INTO mimatricular (alumno, asignatura, grupo, curso)
SELECT A.DNI,
    112,
    'A',
    '23/24'
FROM MISALUMNOS A
    JOIN MIMATRICULAR M ON A.DNI = M.ALUMNO
WHERE months_between (sysdate, A.FECHA_PRIM_MATRICULA) / 12 < 4;
--6--
UPDATE MIMATRICULAR
SET CALIFICACION = 'NP'
WHERE ALUMNO IN (
        SELECT ALUMNO
        FROM MIMATRICULAR
        WHERE CALIFICACION IS NULL
            AND CURSO != '23/24'
    );
--7--
UPDATE MIMATRICULAR
SET CALIFICACION = 'AP'
WHERE (ALUMNO || CURSO || CALIFICACION) IN (
        SELECT DISTINCT ALUMNO || CURSO || CALIFICACION
        FROM MIMATRICULAR
        WHERE CALIFICACION IN ('NP', 'SP')
            AND CURSO != '23/24'
        GROUP BY ALUMNO,
            CURSO,
            CALIFICACION
        HAVING COUNT(*) = 1
    );
--8--
INSERT INTO MIMATRICULAR (ALUMNO, ASIGNATURA, GRUPO, CURSO, CALIFICACION)
SELECT DNI,
    DOCENCIA.ASIGNATURAS.CODIGO,
    'A',
    '23/24',
    NULL
FROM MISALUMNOS
    JOIN DOCENCIA.ASIGNATURAS ON CODIGO = ASIGNATURAS.CODIGO
WHERE DOCENCIA.ASIGNATURAS.CURSO = 3
    AND DNI NOT IN (
        SELECT DISTINCT ALUMNO
        FROM MIMATRICULAR
        WHERE CURSO != '23/24'
            AND CALIFICACION IN ('NP', 'SP')
    );
--9--