CREATE TABLE TOUR AS
SELECT *
FROM DOCENCIA.TOUR2017;
CREATE TABLE INFO_PERSONAL (
    ID NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50 BYTE),
    NACIONALIDAD VARCHAR2(3 BYTE)
);
CREATE TABLE INFOR_PROFESIONAL (
    ID NUMBER(3) PRIMARY KEY,
    EQUIPO VARCHAR2(50 BYTE),
    PAIS VARCHAR2(20 BYTE),
    CATEGORIA VARCHAR2(20 BYTE)
);
INSERT INTO INFO_PERSONAL
SELECT ID,
    NAME NOMBRE,
    NATIONALITY NACIONALIDAD
FROM TOUR;
INSERT INTO INFOR_PROFESIONAL
SELECT ID,
    TEAM EQUIPO,
    COUNTRY PAIS,
    CATEGORY CATEGORIA
FROM TOUR;
UPDATE TOUR_VIEW
SELECT PER.ID,
    EQUIPO,
    PAIS,
    NOMBRE,
    NACIONALIDAD,
    CATEGORIA
FROM INFO_PERSONAL PER
    LEFT JOIN INFOR_PROFESIONAL PRO ON PER.ID = PRO.ID;
SELECT *
FROM TOUR_VIEW;
CREATE TRIGGER TRG_TOUR_VIEW BEFORE
INSERT
    OR
UPDATE
    OR DELETE ON TOUR_VIEW FOR EACH ROW BEGIN
INSERT INTO INFO_PERSONAL
VALUES(
        :NEW.ID,
        :NEW.NOMBRE,
        :NEW.NACIONALIDAD
    );
INSERT INTO INFOR_PROFESIONAL
VALUES(
        :NEW.ID,
        :NEW.EQUIPO,
        :NEW.PAIS,
        :NEW.CATEGORIA
    );
end;