/* Reunion de tablas */
select P.NOMBRE,
  P.APELLIDO1,
  P.APELLIDO2
from DOCENCIA.PROFESORES P
  join DOCENCIA.DEPARTAMENTOS D on P.DEPARTAMENTO = D.CODIGO
where D.NOMBRE = 'Lenguajes y Ciencias de la Computacion';
select distinct A.NOMBRE,
  nvl(to_char(A.PRACTICOS), 'No tiene') as PRACTICOS
from ASIGNATURAS A
  join MATRICULAR M on A.CODIGO = M.ASIGNATURA
  join ALUMNOS AL on M.ALUMNO = AL.DNI
where AL.NOMBRE = 'Nicolas'
  and AL.APELLIDO1 = 'Bersabe'
  and AL.APELLIDO2 = 'Alba';
select P.ID,
  trunc((sysdate - P.ANTIGUEDAD) / 7) as SEMANAS,
  next_day(SYSDATE, to_char(P.ANTIGUEDAD, 'Day')) as PROXIMO
from PROFESORES P
  join DEPARTAMENTOS D on P.DEPARTAMENTO = D.CODIGO
where D.NOMBRE = 'Ingenieria de Comunicaciones';
select distinct M.ALUMNO
from MATRICULAR M
where M.ASIGNATURA = '112'
  and M.CALIFICACION in ('MH', 'SB', 'NT', 'AP');
select distinct P.ID,
  P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || P.APELLIDO2 as NOMBRE,
  A.CODIGO,
  A.NOMBRE
from PROFESORES P
  join IMPARTIR I on P.ID = I.PROFESOR
  join ASIGNATURAS A on I.ASIGNATURA = A.CODIGO;
/* Consultas reflexivas */
select A1.NOMBRE,
  trunc(
    months_between(sysdate, A1.FECHA_NACIMIENTO) / 12
  ) as EDAD,
  A2.NOMBRE,
  trunc(
    months_between(sysdate, A2.FECHA_NACIMIENTO) / 12
  ) as EDAD
from ALUMNOS A1
  join ALUMNOS A2 on A1.DNI < A2.DNI
where A1.APELLIDO1 = A2.APELLIDO1;
select distinct A1.APELLIDO1,
  A2.APELLIDO1
from ALUMNOS A1,
  ALUMNOS A2
where A2.FECHA_NACIMIENTO BETWEEN to_date('2000-01-01', 'YYYY-MM-DD') AND to_date('2001-12-31', 'YYYY-MM-DD')
  and A1.FECHA_NACIMIENTO BETWEEN to_date('2000-01-01', 'YYYY-MM-DD') AND to_date('2001-12-31', 'YYYY-MM-DD')
  and A1.DNI < A2.DNI
  and A1.APELLIDO1 is not null
  and A2.APELLIDO1 is not null;
select P1.NOMBRE || ' ' || P1.APELLIDO1 || ' ' || P1.APELLIDO2 as PROFESOR1,
  P2.NOMBRE || ' ' || P2.APELLIDO1 || ' ' || P2.APELLIDO2 as PROFESOR2
from PROFESORES P1,
  PROFESORES P2
where P1.DEPARTAMENTO = P2.DEPARTAMENTO
  and P1.ID < P2.ID
  and months_between(P1.ANTIGUEDAD, P2.ANTIGUEDAD) / 12 < 2;
select distinct A1.NOMBRE || A1.APELLIDO1 || A1.APELLIDO2 as ELLA,
  A2.NOMBRE || A2.APELLIDO1 || A2.APELLIDO2 as EL
from ALUMNOS A1,
  ALUMNOS A2
  join MATRICULAR M on M.ALUMNO = A2.DNI
where A1.DNI < A2.DNI
  and A1.GENERO != A2.GENERO
  and A1.GENERO = 'FEM'
  and A1.GENERO = 'MASC'
  and M.ASIGNATURA = '112';
select distinct A1.NOMBRE,
  A2.NOMBRE,
  A3.NOMBRE,
  A1.COD_MATERIA
from ASIGNATURAS A1,
  ASIGNATURAS A2,
  ASIGNATURAS A3
where A1.COD_MATERIA = A2.COD_MATERIA
  and A2.COD_MATERIA = A3.COD_MATERIA
  and A1.NOMBRE != A2.NOMBRE
  and A2.NOMBRE != A3.NOMBRE
  and A1.NOMBRE != A3.NOMBRE;
/* Reunión de tablas y orden */
select A.NOMBRE || ' ' || A.APELLIDO1 || ' ' || A.APELLIDO2 as ALUMNO,
  ASIG.NOMBRE as ASIGNATURA,
  decode(
    M.CALIFICACION,
    'MH',
    'Matricula de Honor',
    'SB',
    'Sobresaliente',
    'NT',
    'Notable',
    'AP',
    'Aprobado',
    'NP',
    'No Presentado',
    'No presentado'
  ) as CALIFICACION
from ALUMNOS A
  join MATRICULAR M on A.DNI = M.ALUMNO
  join ASIGNATURAS ASIG on M.ASIGNATURA = ASIG.CODIGO
where months_between(sysdate, A.FECHA_NACIMIENTO) / 12 < 22
order by A.APELLIDO1,
  A.APELLIDO2,
  A.NOMBRE;
select distinct A.NOMBRE,
  A.APELLIDO1,
  A.APELLIDO2
from PROFESORES P
  join IMPARTIR I on P.ID = I.PROFESOR
  join MATRICULAR M on I.ASIGNATURA = M.ASIGNATURA
  join ALUMNOS A on M.ALUMNO = A.DNI
where P.NOMBRE = 'Enrique'
  and P.APELLIDO1 = 'Soler'
order by A.APELLIDO1,
  A.APELLIDO2,
  A.NOMBRE;
select distinct A.NOMBRE,
  A.APELLIDO1,
  A.APELLIDO2
from ALUMNOS A
  join MATRICULAR M on A.DNI = M.ALUMNO
  join ASIGNATURAS ASIG on M.ASIGNATURA = ASIG.CODIGO
  join IMPARTIR I on ASIG.CODIGO = I.ASIGNATURA
  join DOCENCIA.PROFESORES P on I.PROFESOR = P.ID
  join DEPARTAMENTOS D on P.DEPARTAMENTO = D.CODIGO
where D.NOMBRE = 'Lenguajes y Ciencias de la Computacion'
order by A.NOMBRE,
  A.APELLIDO1,
  A.APELLIDO2;
select ASI.NOMBRE ASIGNATURA,
  M.NOMBRE MATERIA,
  P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || P.APELLIDO2 PROFESOR,
  I.CARGA_CREDITOS
from ASIGNATURAS ASI,
  MATERIAS M,
  PROFESORES P,
  IMPARTIR I
where ASI.COD_MATERIA = M.CODIGO
  and I.ASIGNATURA = ASI.CODIGO
  and I.PROFESOR = P.ID
  and I.CARGA_CREDITOS is not null
order by ASI.COD_MATERIA,
  ASI.NOMBRE desc;
select ASI.NOMBRE NOMBRE,
  D.NOMBRE DEPARTAMENTO,
  ASI.CREDITOS "CREDITOS TOTALES",
  trunc((ASI.PRACTICOS / ASI.CREDITOS) * 100, 2) "PORCENTAJE PRACTICOS"
from ASIGNATURAS ASI
  join DEPARTAMENTOS D on ASI.DEPARTAMENTO = D.CODIGO
where ASI.CREDITOS is not null
  and ASI.PRACTICOS is not null
  and ASI.TEORICOS is not null
order by trunc((ASI.PRACTICOS / ASI.CREDITOS) * 100, 2) desc;
/* Operaciones de conjuntos */
select CODIGO
from ASIGNATURAS
minus
select ASIGNATURA
from IMPARTIR;
SELECT EMAIL
FROM PROFESORES
WHERE EMAIL IS NOT NULL
UNION ALL
SELECT EMAIL
FROM ALUMNOS
WHERE EMAIL IS NOT NULL;
(
  SELECT UPPER(APELLIDO1)
  FROM ALUMNOS
  WHERE APELLIDO1 IS NOT NULL
  UNION
  SELECT UPPER(APELLIDO2)
  FROM ALUMNOS
  WHERE APELLIDO2 IS NOT NULL
)
INTERSECT
(
  SELECT UPPER(APELLIDO1)
  FROM PROFESORES
  WHERE APELLIDO1 IS NOT NULL
  UNION
  SELECT UPPER(APELLIDO2)
  FROM PROFESORES
  WHERE APELLIDO2 IS NOT NULL
);
(
  SELECT UPPER(APELLIDO1)
  FROM ALUMNOS
  WHERE APELLIDO1 IS NOT NULL
    AND UPPER(APELLIDO1) LIKE '%LL%'
  UNION
  SELECT UPPER(APELLIDO2)
  FROM ALUMNOS
  WHERE APELLIDO2 IS NOT NULL
    AND UPPER(APELLIDO2) LIKE '%LL%'
)
UNION
(
  SELECT UPPER(APELLIDO1)
  FROM PROFESORES
  WHERE APELLIDO1 IS NOT NULL
    AND UPPER(APELLIDO1) LIKE '%LL%'
  UNION
  SELECT UPPER(APELLIDO2)
  FROM PROFESORES
  WHERE APELLIDO2 IS NOT NULL
    AND UPPER(APELLIDO2) LIKE '%LL%'
);
(
  SELECT UPPER(REPLACE(APELLIDO1, 'LL', 'Y'))
  FROM ALUMNOS
  WHERE APELLIDO1 IS NOT NULL
    AND UPPER(APELLIDO1) LIKE '%LL%'
  UNION
  SELECT UPPER(REPLACE(APELLIDO2, 'LL', 'Y'))
  FROM ALUMNOS
  WHERE APELLIDO2 IS NOT NULL
    AND UPPER(APELLIDO2) LIKE '%LL%'
)
UNION
(
  SELECT UPPER(REPLACE(APELLIDO1, 'LL', 'Y'))
  FROM PROFESORES
  WHERE APELLIDO1 IS NOT NULL
    AND UPPER(APELLIDO1) LIKE '%LL%'
  UNION
  SELECT UPPER(REPLACE(APELLIDO2, 'LL', 'Y'))
  FROM PROFESORES
  WHERE APELLIDO2 IS NOT NULL
    AND UPPER(APELLIDO2) LIKE '%LL%'
);
/* Reuniones externas */
SELECT ASI.NOMBRE,
  PROFESOR
FROM ASIGNATURAS ASI
  LEFT OUTER JOIN IMPARTIR I ON ASI.CODIGO = I.ASIGNATURA
WHERE NVL(CREDITOS, 0) <> NVL(PRACTICOS, 0) + NVL(TEORICOS, 0);
SELECT P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || P.APELLIDO2 "NOMBRE PROFESOR",
  D.NOMBRE || ' ' || D.APELLIDO1 || ' ' || D.APELLIDO2 "NOMBRE DIRECTOR"
FROM PROFESORES P
  LEFT OUTER JOIN PROFESORES D ON P.DIRECTOR_TESIS = D.ID
ORDER BY P.NOMBRE,
  P.APELLIDO1,
  P.APELLIDO2;
SELECT 'El director de ' || P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || P.APELLIDO2 || ' es ' || D.NOMBRE || ' ' || D.APELLIDO1 || ' ' || D.APELLIDO2 "NOMBRE COMPLETO PROFESOR-DIRECTOR",
  NVL(I.TRAMOS, 0) "TRAMOS"
FROM PROFESORES P
  JOIN PROFESORES D ON (P.DIRECTOR_TESIS = D.ID)
  LEFT OUTER JOIN INVESTIGADORES I ON (D.ID = I.ID_PROFESOR);
SELECT A1.NOMBRE || ' ' || A1.APELLIDO1 || ' ' || A1.APELLIDO2 "NOMBRE DEL ALUMNO 1",
  A2.NOMBRE || ' ' || A2.APELLIDO1 || ' ' || A2.APELLIDO2 "NOMBRE DE ALUMNO 2:"
FROM ALUMNOS A1
  LEFT OUTER JOIN ALUMNOS A2 ON (
    A1.FECHA_PRIM_MATRICULA = A2.FECHA_PRIM_MATRICULA
    AND A1.DNI < A2.DNI
  )
ORDER BY A1.NOMBRE,
  A1.APELLIDO1,
  A1.APELLIDO2;
SELECT A.NOMBRE "NOMBRE ASIGNATURA",
  NVL(I.CURSO, ' ') "CURSO",
  NVL(I.GRUPO, ' ') "GRUPO",
  P.NOMBRE || ' ' || P.APELLIDO1 "NOMBRE PROFESOR"
FROM ASIGNATURAS A
  LEFT OUTER JOIN IMPARTIR I ON (A.CODIGO = I.ASIGNATURA)
  LEFT OUTER JOIN PROFESORES P ON (I.PROFESOR = P.ID);
/* Subconsultas */
SELECT NOMBRE,
  ID
FROM PROFESORES
WHERE ID NOT IN (
    SELECT PROFESOR
    FROM IMPARTIR
  );
SELECT NOMBRE || ' ' || APELLIDO1 || ' ' || APELLIDO2
FROM ALUMNOS
WHERE ROWNUM < 3
  AND UPPER(GENERO) = 'FEM'
  AND DNI IN (
    SELECT ALUMNO
    FROM MATRICULAR
    WHERE ASIGNATURA = 115
  );
SELECT *
FROM PROFESORES
WHERE ID NOT IN (
    SELECT DIRECTOR_TESIS
    FROM PROFESORES
    WHERE DIRECTOR_TESIS IS NOT NULL
  );
SELECT NOMBRE,
  CODIGO
FROM ASIGNATURAS A
WHERE EXISTS (
    SELECT *
    FROM ASIGNATURAS
    WHERE NVL(CREDITOS, 0) > NVL(A.CREDITOS, 0)
      AND NVL(CURSO, 0) = NVL(A.CURSO, 0)
  );
(
  SELECT NOMBRE,
    CODIGO
  FROM ASIGNATURAS
)
MINUS
(
  SELECT NOMBRE,
    CODIGO
  FROM ASIGNATURAS A
  WHERE EXISTS(
      SELECT *
      FROM ASIGNATURAS
      WHERE NVL(CREDITOS, 0) > NVL(A.CREDITOS, 0)
        AND NVL(CURSO, 0) = NVL(A.CURSO, 0)
    )
)