create table APLICACIONES
(
    NOMBRE_APLIC   VARCHAR2(100) not null
        primary key,
    COMPANIA       VARCHAR2(100),
    PRECIO         NUMBER(5, 2),
    WEB_APLICACION VARCHAR2(100)
)
/

create unique index APLICACIONES_WEB_APLICACION_UINDEX
    on APLICACIONES (WEB_APLICACION)
/

INSERT INTO UBD1006.APLICACIONES (NOMBRE_APLIC, COMPANIA, PRECIO, WEB_APLICACION) VALUES ('Paintor', 'Micrisoft', 0.00, 'https://www.micrisoft.com/paintor');
INSERT INTO UBD1006.APLICACIONES (NOMBRE_APLIC, COMPANIA, PRECIO, WEB_APLICACION) VALUES ('PoorEdit', 'Sofw', 30.00, 'http://www.soft.com/PE');
INSERT INTO UBD1006.APLICACIONES (NOMBRE_APLIC, COMPANIA, PRECIO, WEB_APLICACION) VALUES ('SaveEdit', 'Borllan', 40.00, 'http://www.Borllan.com');
INSERT INTO UBD1006.APLICACIONES (NOMBRE_APLIC, COMPANIA, PRECIO, WEB_APLICACION) VALUES ('SimpleTexto', 'Micrisoft', 100.00, 'http://www.micrisoft.com');
INSERT INTO UBD1006.APLICACIONES (NOMBRE_APLIC, COMPANIA, PRECIO, WEB_APLICACION) VALUES ('TxtE', 'Sofw', 60.00, 'http://www.soft.com/TxTE');
