create table COMPATIBLE
(
    NOMBRE_DOCUMENTO  VARCHAR2(100) not null,
    DIRECTORIO        VARCHAR2(100) not null,
    NOMBRE_APLICACION VARCHAR2(100) not null
        constraint COMPATIBLE_APLICACIONES_NOMBRE_APLIC_FK
            references APLICACIONES,
    primary key (NOMBRE_DOCUMENTO, NOMBRE_APLICACION, DIRECTORIO),
    constraint COMPATIBLE_DOCUMENTO_NOMBRE_DIRECTORIO_FK
        foreign key (NOMBRE_DOCUMENTO, DIRECTORIO) references DOCUMENTO
)
/

INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Facturas junio', '/user/enciso', 'PoorEdit');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Facturas junio', '/user/enciso', 'SaveEdit');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Facturas junio', '/user/enciso', 'TxtE');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Prueba.txt', '/user/practicas', 'PoorEdit');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Prueba.txt', '/user/practicas', 'SaveEdit');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Tesis.doc', '/user/enciso', 'SimpleTexto');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('Tesis2.doc', '/user/enciso', 'SimpleTexto');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('logo.gif', '/user/enciso', 'Paintor');
INSERT INTO UBD1006.COMPATIBLE (NOMBRE_DOCUMENTO, DIRECTORIO, NOMBRE_APLICACION) VALUES ('logo.gif', '/user/practicas', 'Paintor');
