create table DOCUMENTO
(
    NOMBRE         VARCHAR2(100) not null,
    DIRECTORIO     VARCHAR2(100) not null,
    FECHA_CREACION DATE,
    COMENTARIO     VARCHAR2(100),
    TAMANO         NUMBER(3),
    APLICACION     VARCHAR2(100)
        constraint DOCUMENTO_APLICACIONES_NOMBRE_APLIC_FK
            references APLICACIONES,
    constraint PRIMARIA_DOCUMENTO
        primary key (NOMBRE, DIRECTORIO)
)
/

INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('Prueba.txt', '/user/practicas', DATE '2002-06-03', 'fichero de prueba', 30, 'SaveEdit');
INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('logo.gif', '/user/practicas', DATE '2002-06-13', 'ES UN GRAFICO', 40, 'Paintor');
INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('Tesis.doc', '/user/enciso', DATE '2002-06-15', 'fichero de tesis', 43, 'SimpleTexto');
INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('Tesis2.doc', '/user/enciso', DATE '2002-05-15', 'fichero de tesis 2', 50, 'SimpleTexto');
INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('Facturas junio', '/user/enciso', DATE '2002-05-03', 'todas las facturas', 50, 'TxtE');
INSERT INTO UBD1006.DOCUMENTO (NOMBRE, DIRECTORIO, FECHA_CREACION, COMENTARIO, TAMANO, APLICACION) VALUES ('logo.gif', '/user/enciso', DATE '2002-04-03', 'ESUN GRAFICO, No Txt', 10, 'Paintor');
