create table PAGINA
(
    NOMBRE          VARCHAR2(100) not null,
    DIRECTORIO      VARCHAR2(100) not null,
    NUMERO_PAGINA   NUMBER(5)     not null,
    CABECERA_PAGINA VARCHAR2(500),
    PIE_PAGINA      VARCHAR2(100),
    ESPACIADO       NUMBER,
    primary key (NUMERO_PAGINA, NOMBRE, DIRECTORIO),
    constraint PAGINA_DOC_TEXTO_NOMBRE_DIRECTORIO_FK
        foreign key (NOMBRE, DIRECTORIO) references DOC_TEXTO
)
/

INSERT INTO UBD1006.PAGINA (NOMBRE, DIRECTORIO, NUMERO_PAGINA, CABECERA_PAGINA, PIE_PAGINA, ESPACIADO) VALUES ('Prueba.txt', '/user/practicas', 1, null, null, null);
INSERT INTO UBD1006.PAGINA (NOMBRE, DIRECTORIO, NUMERO_PAGINA, CABECERA_PAGINA, PIE_PAGINA, ESPACIADO) VALUES ('Prueba.txt', '/user/practicas', 2, null, null, null);
INSERT INTO UBD1006.PAGINA (NOMBRE, DIRECTORIO, NUMERO_PAGINA, CABECERA_PAGINA, PIE_PAGINA, ESPACIADO) VALUES ('Tesis.doc', '/user/enciso', 1, null, null, null);
